language: java

sudo: false

script: "mvn package --settings travis/settings.xml"

dist: trusty

jdk:
  - oraclejdk8

env:
  global:
  - secure: "sWHHlcgm2rRG8boEwFCCKfTmuVrTI5G0YNG7r3IKflhEm2g/PoWmaE0llAYK4K/yWhJGjTuzFBfcovGT7S7EXaicjy7pps3Oov4dGZtOp2/4mAsMh8Qec2AFl1CbK0Mt5maxwX3QPeYrbOnezIdHvTh0gMPU6PfcJg7xPn7Fh/JCh+sGvHcKpE+BVoHtrwnwfcHRMgh1FHZY3ZWqAvP7Zif67l/wKnW7iFwksJfTZqHy2Z4HRqLXRnzRMvTHpaoOuoopuEAQvd3kDO4iKnyWTqn28Xgb2OLGlnj+mQ1zJP7LyUQrIYejdEs7okzxCfc2XKWh+W1WRzyDvn2jnCosKvHle/FpHCxgdHK1272WaalzCKptw2+QmlJGdlkjsxcElVkY07YZ6AShDqFZgfTC0pRBNS7U5w9zTr6wgUAu2Ti7bTBW0vtYoKIgZT/YUwFu5CS8MAYUsAptwytw9S/eaNZe8UV6tDO6FVddtTtYASslgJnuL9pTfCaQyXxKz99KzRnwIv8KtTxRvv+YqzclgRFM9Ty+LHLr5m9B8QxH7VUou9Q8TOpMqwrMjyhaISQaDUk0T+9u6Ko/7//3y0lnvh2BCUmQKnzp17FgkN3Ii9KmIejKzTL4Nd8CQtD/UF1IY2wzrymphHnKQpyVVuwFglDCoy2z6RRUY39kIRGC05k="
  - secure: "NITMmonj9xv7mQ2X1iETVkGrjKNPgcv40i/ad/Hc+KxtkagfPDhagEZJS4pWuGsTrC5NoJpUdCNm6nkFQVdRWVOSj11HGpYkY1SyLg7pRq1XXALheUWi7JN9z+7jPoyfSD6ACh0RA7iyKuRPiYU/8pfu5+ewt14tktldy7VBRtnxwt10TyBkLVglRUaJq2S4tZ4Rin4G6CPwsYCJgbyjQWcxi1RzzdN1c/rO3U5Eo5WC1YLqDdHxn9X9VAGkE6a/fvH7xROsPYimzqwTKSdczu7uZ00YT88vzLqxarB5MgOtvb6jlXbj/G3VotcBGFpb/M7fKYZBBCzryc4zgv75RSTTnEYx4U1aKdQffDob+Etpk7ARfynmSG4D10vmK2eXPn9uFs4LL0FCAlvETHna8kN1u+ET9rUjvV9TR6v0yuT6cR2sDHSEr4VUT5t0BNvNqPH9HFSIeyZW24APis+t1rR/OuoDog4jvDuReBwrhfDUf1KsgaPJfz+YlMr6jlgMaL2+DL2SUirdEaBkIwnZlnuEoiKdVJ4Q/gkkI/72+zXFn20EqKQZKJkCC0lI4pgsarc0J2HRm/sRU0oglJUfChVjrczzAVfmgmuJFGcEQiEBZrMQ59RCAKCQ9LS6vxh5SfQKK5OOjiWJcR2h7pOp9/WwRJJXG6h/rom31vueB0g="

after_success:
- chmod -R 777 ./travis/deploy-to-sonatype.sh
- ./travis/deploy-to-sonatype.sh
